version: '3'

services:
  mysql:
    image: mysql/mysql-server:latest
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=timet0kill
      - MYSQL_DATABASE=que
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: